/*
 * This source file was generated by the Gradle 'init' task
 */
package com.furnituredesigner;

import com.furnituredesigner.client.ui.LoginPanel;
import com.furnituredesigner.client.ui.MainFrame;
import com.furnituredesigner.common.model.User;

import javax.swing.*;
import java.awt.*;

public class App {
    public static void main(String[] args) {
        System.out.println("Starting Furniture Designer Application...");
        
        // Launch the GUI on the Event Dispatch Thread
        SwingUtilities.invokeLater(() -> {
            try {
                // Set system look and feel
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                
                // Create and show login frame
                JFrame loginFrame = new JFrame("Furniture Designer Login");
                loginFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                loginFrame.setSize(400, 300);
                loginFrame.setLocationRelativeTo(null);
                
                // Create login panel with callback for successful login
                LoginPanel loginPanel = new LoginPanel(user -> {
                    // Close login frame
                    loginFrame.dispose();
                    
                    // Create and show main application frame
                    MainFrame mainFrame = new MainFrame(user);
                    mainFrame.setVisible(true);
                });
                
                loginFrame.add(loginPanel);
                loginFrame.setVisible(true);
                
                System.out.println("GUI launched successfully");
                
            } catch (Exception e) {
                System.err.println("Error starting GUI: " + e.getMessage());
                e.printStackTrace();
            }
        });
    }
}
